### PR TITLE
Template Driven Extraction

### PR DESCRIPTION
**Pull request by Floppy**
We are exploring generating linked data triples using Marklogic's Template Drive Extraction feature. This PR adds a prototype template and configuration for triple extraction.

### CODE REVIEW

**Comment by Floppy** [comment]
@jacksonj04 and I did an experiment where we changed a template, and Marklogic appeared to remove old triples and replace with the new ones, which is very promising.

**Comment by Floppy** [comment]
This needs resubmitting to the new ds-caselaw-marklogic repo. Leaving open for now until I move it over.

**Comment by anthonyhashemi** [comment]
Hi @Floppy, I noticed that we don't have a `core.xml` file in the marklogic repo. Do we still want to create a version of this PR there and then close this one?

**Comment by dragon-dxw** [comment]
I think that's a smart move.

**Comment by dragon-dxw** [comment]
PR migrated to https://github.com/nationalarchives/ds-caselaw-marklogic/pull/22

**Pull request closed without merging**
